[2024-02-06T17:45:18.156+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_snowflake_etl.copy_csv_into_snowflake_table manual__2024-02-06T17:45:00.876602+00:00 [queued]>
[2024-02-06T17:45:18.168+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_snowflake_etl.copy_csv_into_snowflake_table manual__2024-02-06T17:45:00.876602+00:00 [queued]>
[2024-02-06T17:45:18.169+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-06T17:45:18.186+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): copy_csv_into_snowflake_table> on 2024-02-06 17:45:00.876602+00:00
[2024-02-06T17:45:18.192+0000] {standard_task_runner.py:60} INFO - Started process 99 to run task
[2024-02-06T17:45:18.197+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_snowflake_etl', 'copy_csv_into_snowflake_table', 'manual__2024-02-06T17:45:00.876602+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/S3_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpebcpoubj']
[2024-02-06T17:45:18.199+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask copy_csv_into_snowflake_table
[2024-02-06T17:45:18.257+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_snowflake_etl.copy_csv_into_snowflake_table manual__2024-02-06T17:45:00.876602+00:00 [running]> on host 79019d796c34
[2024-02-06T17:45:18.344+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='s3_snowflake_etl' AIRFLOW_CTX_TASK_ID='copy_csv_into_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T17:45:00.876602+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T17:45:00.876602+00:00'
[2024-02-06T17:45:18.346+0000] {sql.py:276} INFO - Executing: COPY INTO rabbit_mission.lunar.full_moon_time from @rabbit_mission.lunar.snowflake_stage_yml FILE_FORMAT = csv_format
                
[2024-02-06T17:45:18.359+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-06T17:45:18.374+0000] {base.py:83} INFO - Using connection ID 'conn_id_snowflake' for task execution.
[2024-02-06T17:45:18.375+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.34
[2024-02-06T17:45:18.377+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-02-06T17:45:18.812+0000] {cursor.py:1028} INFO - query: [ALTER SESSION SET autocommit=False]
[2024-02-06T17:45:18.914+0000] {cursor.py:1041} INFO - query execution done
[2024-02-06T17:45:18.916+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2024-02-06T17:45:18.917+0000] {sql.py:450} INFO - Running statement: COPY INTO rabbit_mission.lunar.full_moon_time from @rabbit_mission.lunar.snowflake_stage_yml FILE_FORMAT = csv_format, parameters: None
[2024-02-06T17:45:18.918+0000] {cursor.py:1028} INFO - query: [COPY INTO rabbit_mission.lunar.full_moon_time from @rabbit_mission.lunar.snowfla...]
[2024-02-06T17:45:19.988+0000] {cursor.py:1041} INFO - query execution done
[2024-02-06T17:45:19.996+0000] {connection.py:718} INFO - closed
[2024-02-06T17:45:20.057+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2024-02-06T17:45:20.122+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 455, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): 01b22c89-3200-fd50-0000-0007a44ec28d: SQL compilation error:
File format 'CSV_FORMAT' does not exist or not authorized.
[2024-02-06T17:45:20.134+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_snowflake_etl, task_id=copy_csv_into_snowflake_table, execution_date=20240206T174500, start_date=20240206T174518, end_date=20240206T174520
[2024-02-06T17:45:20.154+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task copy_csv_into_snowflake_table (002003 (02000): 01b22c89-3200-fd50-0000-0007a44ec28d: SQL compilation error:
File format 'CSV_FORMAT' does not exist or not authorized.; 99)
[2024-02-06T17:45:20.182+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T17:45:20.213+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
