[2024-02-28T17:09:33.607+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_snowflake_etl.create_snowflake_table manual__2024-02-28T17:05:18.498215+00:00 [queued]>
[2024-02-28T17:09:33.619+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_snowflake_etl.create_snowflake_table manual__2024-02-28T17:05:18.498215+00:00 [queued]>
[2024-02-28T17:09:33.620+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-28T17:09:33.639+0000] {taskinstance.py:2191} INFO - Executing <Task(SnowflakeOperator): create_snowflake_table> on 2024-02-28 17:05:18.498215+00:00
[2024-02-28T17:09:33.646+0000] {standard_task_runner.py:60} INFO - Started process 150 to run task
[2024-02-28T17:09:33.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'gcs_snowflake_etl', 'create_snowflake_table', 'manual__2024-02-28T17:05:18.498215+00:00', '--job-id', '275', '--raw', '--subdir', 'DAGS_FOLDER/GCS_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmp2odzt9__']
[2024-02-28T17:09:33.657+0000] {standard_task_runner.py:88} INFO - Job 275: Subtask create_snowflake_table
[2024-02-28T17:09:33.727+0000] {task_command.py:423} INFO - Running <TaskInstance: gcs_snowflake_etl.create_snowflake_table manual__2024-02-28T17:05:18.498215+00:00 [running]> on host 1753c686362f
[2024-02-28T17:09:33.825+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='gcs_snowflake_etl' AIRFLOW_CTX_TASK_ID='create_snowflake_table' AIRFLOW_CTX_EXECUTION_DATE='2024-02-28T17:05:18.498215+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-28T17:05:18.498215+00:00'
[2024-02-28T17:09:33.827+0000] {sql.py:276} INFO - Executing: 
            DROP TABLE IF EXISTS full_moon_time;
            CREATE TABLE IF NOT EXISTS full_moon_time(
                Date VARCHAR,
                MoonriseEarly TIME,
                Moonset TIME,
                MoonriseLate TIME,
                Phase VARCHAR,
                PhaseTime TIME,
                CivilDawn TIME,
                CivilDusk TIME 	
            )
        
[2024-02-28T17:09:33.851+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
  File "/usr/local/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `conn_id_snowflake` isn't defined
[2024-02-28T17:09:33.856+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=gcs_snowflake_etl, task_id=create_snowflake_table, execution_date=20240228T170518, start_date=20240228T170933, end_date=20240228T170933
[2024-02-28T17:09:33.879+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 275 for task create_snowflake_table (The conn_id `conn_id_snowflake` isn't defined; 150)
[2024-02-28T17:09:33.905+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-28T17:09:33.944+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
