[2024-02-06T20:18:21.202+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T20:13:41.570151+00:00 [queued]>
[2024-02-06T20:18:21.218+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T20:13:41.570151+00:00 [queued]>
[2024-02-06T20:18:21.219+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 3
[2024-02-06T20:18:21.241+0000] {taskinstance.py:2191} INFO - Executing <Task(EmailOperator): notify_by_email> on 2024-02-06 20:13:41.570151+00:00
[2024-02-06T20:18:21.254+0000] {standard_task_runner.py:60} INFO - Started process 159 to run task
[2024-02-06T20:18:21.258+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_snowflake_etl', 'notify_by_email', 'manual__2024-02-06T20:13:41.570151+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/S3_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpgoqx6dsv']
[2024-02-06T20:18:21.261+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask notify_by_email
[2024-02-06T20:18:21.339+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T20:13:41.570151+00:00 [running]> on host 5828c95b5c96
[2024-02-06T20:18:21.460+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='s3_snowflake_etl' AIRFLOW_CTX_TASK_ID='notify_by_email' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T20:13:41.570151+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T20:13:41.570151+00:00'
[2024-02-06T20:18:21.480+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-06T20:18:21.481+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-06T20:18:21.482+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-06T20:18:22.425+0000] {email.py:281} INFO - Sent an alert email to ['grittapop.p@gmail.com']
[2024-02-06T20:18:23.017+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError e24-20020a62aa18000000b006e0332b4c06sm2383862pff.212 - gsmtp', '***@example.com')
[2024-02-06T20:18:23.031+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=s3_snowflake_etl, task_id=notify_by_email, execution_date=20240206T201341, start_date=20240206T201821, end_date=20240206T201823
[2024-02-06T20:18:23.059+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task notify_by_email ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError e24-20020a62aa18000000b006e0332b4c06sm2383862pff.212 - gsmtp', '***@example.com'); 159)
[2024-02-06T20:18:23.125+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T20:18:23.158+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
