[2024-02-06T21:55:22.662+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:55:03.350456+00:00 [queued]>
[2024-02-06T21:55:22.682+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:55:03.350456+00:00 [queued]>
[2024-02-06T21:55:22.683+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-02-06T21:55:22.707+0000] {taskinstance.py:2191} INFO - Executing <Task(EmailOperator): notify_by_email> on 2024-02-06 21:55:03.350456+00:00
[2024-02-06T21:55:22.714+0000] {standard_task_runner.py:60} INFO - Started process 73 to run task
[2024-02-06T21:55:22.720+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_snowflake_etl', 'notify_by_email', 'manual__2024-02-06T21:55:03.350456+00:00', '--job-id', '170', '--raw', '--subdir', 'DAGS_FOLDER/S3_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpn6rjcvt7']
[2024-02-06T21:55:22.722+0000] {standard_task_runner.py:88} INFO - Job 170: Subtask notify_by_email
[2024-02-06T21:55:22.803+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:55:03.350456+00:00 [running]> on host 515a56cbc7c8
[2024-02-06T21:55:22.907+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='s3_snowflake_etl' AIRFLOW_CTX_TASK_ID='notify_by_email' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T21:55:03.350456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T21:55:03.350456+00:00'
[2024-02-06T21:55:22.922+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-06T21:55:22.923+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-06T21:55:22.924+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-06T21:55:22.925+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 272, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 316, in _get_smtp_connection
    return smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.8/smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.8/smtplib.py", line 310, in _get_socket
    return socket.create_connection((host, port), timeout,
  File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2024-02-06T21:55:22.938+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_snowflake_etl, task_id=notify_by_email, execution_date=20240206T215503, start_date=20240206T215522, end_date=20240206T215522
[2024-02-06T21:55:22.957+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 170 for task notify_by_email ([Errno 99] Cannot assign requested address; 73)
[2024-02-06T21:55:22.974+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T21:55:23.006+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
