[2024-02-06T21:25:45.196+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:13:25.996012+00:00 [queued]>
[2024-02-06T21:25:45.216+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:13:25.996012+00:00 [queued]>
[2024-02-06T21:25:45.217+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-02-06T21:25:45.242+0000] {taskinstance.py:2191} INFO - Executing <Task(EmailOperator): notify_by_email> on 2024-02-06 21:13:25.996012+00:00
[2024-02-06T21:25:45.250+0000] {standard_task_runner.py:60} INFO - Started process 62 to run task
[2024-02-06T21:25:45.255+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_snowflake_etl', 'notify_by_email', 'manual__2024-02-06T21:13:25.996012+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/S3_to_Snowflake_DAG.py', '--cfg-path', '/tmp/tmpsfy59yjo']
[2024-02-06T21:25:45.258+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask notify_by_email
[2024-02-06T21:25:45.342+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_snowflake_etl.notify_by_email manual__2024-02-06T21:13:25.996012+00:00 [running]> on host 03b8549ccfde
[2024-02-06T21:25:45.486+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stellar' AIRFLOW_CTX_DAG_ID='s3_snowflake_etl' AIRFLOW_CTX_TASK_ID='notify_by_email' AIRFLOW_CTX_EXECUTION_DATE='2024-02-06T21:13:25.996012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-06T21:13:25.996012+00:00'
[2024-02-06T21:25:45.509+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/email.py:154: RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2024-02-06T21:25:45.511+0000] {configuration.py:1046} WARNING - section/key [smtp/smtp_user] not found in config
[2024-02-06T21:25:45.512+0000] {email.py:270} INFO - Email alerting: attempt 1
[2024-02-06T21:25:46.436+0000] {email.py:281} INFO - Sent an alert email to ['grittapop.p@gmail.com']
[2024-02-06T21:25:47.023+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/email.py", line 79, in execute
    send_email(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 80, in send_email
    return backend(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 154, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/email.py", line 282, in send_mime_email
    smtp_conn.sendmail(e_from, e_to, mime_msg.as_string())
  File "/usr/local/lib/python3.8/smtplib.py", line 885, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError y9-20020aa793c9000000b006e04082ad5esm2504132pff.142 - gsmtp', '***@example.com')
[2024-02-06T21:25:47.036+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_snowflake_etl, task_id=notify_by_email, execution_date=20240206T211325, start_date=20240206T212545, end_date=20240206T212547
[2024-02-06T21:25:47.070+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 133 for task notify_by_email ((530, b'5.7.0 Authentication Required. For more information, go to\n5.7.0  https://support.google.com/mail/?p=WantAuthError y9-20020aa793c9000000b006e04082ad5esm2504132pff.142 - gsmtp', '***@example.com'); 62)
[2024-02-06T21:25:47.117+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-06T21:25:47.141+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
